# Generated by Django 5.1 on 2024-08-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystemapp', '0016_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='starting_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
